extends Node

const ENEMIES = "enemies"
const PLAYER = "player"
const BOSS = "boss"
const BOSS_BAR = "boss_bar"
const SPAWN_CONTROL = "spawn_control"
const FLOOR_CONTROL = "floor_control"
const MINIGAMES = "minigames"
const BALLOON = "balloon"
const BGM = "bgm"
const SE = "se"
const INPUT_GROUP = "input_group"
const MENU = "menu"
const CUTSCENE = "cutscene"
const VIDEO = "video"
const PERK = "perk"
const CROWD = "crowd"
const CAMERA = "camera"
const CHAR_PIC = "character_pic"
const BLACK_SCREEN_CONTROL = "black_screen_control"
const BLUR_SCREEN_CONTROL = "blur_screen_control"

const BULLET = "bullet"
const ENEMIES_BULLET = "enemies_bullet"
const FLYER = "flyer"
const MULTI_SHOT_FLYER = "multi_shot_flyer"
const CIRCLE_FLYER = "circle_flyer"
const DASHER = "dasher"
const CHARGER = "charger"
const BOSS_FLY = "bossfly"

const TUTORIAL = "tutorial"
const BALLOON_BOX = "balloon_box"
const DIALOGUE_BOX = "dialogue_box"
const FOCUS_FIRST = "focus_first"
